fix(crash): crash not check fragment is null
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v4.app.Fragment.isVisible()' on a null object reference

at rikka.akashitoolkit.ui.MainActivity.onBackPressed(MainActivity.java:231)